apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: worlddatetime
  namespace: worlddatetime

  labels: 
    release: observability-stage

spec:

  namespaceSelector:
    matchNames: 
      - worlddatetime
      
  selector:
    matchLabels:
      app: worlddatetime

  endpoints:
    - port: http
      path: /metrics
      interval: 15s