apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: weatherserver
  namespace: weatherserver

  labels: 
    release: observability-stage

spec:

  namespaceSelector:
    matchNames: 
      - weatherserver
      
  selector:
    matchLabels:
      app: weatherserver

  endpoints:
    - port: http
      path: /metrics
      interval: 15s