apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: weatherserver

  labels: 
    release: observability-stage

spec:

  selector:
    matchLabels:
      app: weatherserver

  endpoints:
    - port: http
      path: /metrics
      interval: 15s