apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-dns
  namespace: argocd

spec:

  project: default
  source:

    repoURL: https://kubernetes-sigs.github.io/external-dns

    chart: external-dns

    targetRevision: 1.15.0

    helm:
      values: |

        provider: google

        policy: sync

        txtOwnerId: stage-cluster
        serviceAccount:
          create: true
          name: external-dns
          annotations:
            iam.gke.io/gcp-service-account: externaldns@worlddatetime-stage.iam.gserviceaccount.com
  
  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

    syncOptions:
    - CreateNamespace=true