apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - stage/worlddatetime.yaml
  - prod/worlddatetime.yaml
  - projects/platform-project.yaml
  - projects/platform-project-prod.yaml

