---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: worlddatetime
spec:
  template:
    spec:
      containers:
      - name: worlddatetime
        image: ":v0.0.0-a6a781d@sha256:f3857a8617e9f9a0da89ed53206fddc692ab05341d701c081b245a7b0f12a012"
