apiVersion: apps/v1
kind: Deployment
metadata:
  name: worlddatetime
spec:
  template:
    spec:
      containers:
        - name: worlddatetime
          image: asia-south1-docker.pkg.dev/worlddatetime-stage/worlddatetime/worlddatetime:v0.0.0-21aa836@sha256:6e2d2838589869445335af4f1c1b9a7784187e026ca61639dabecd745fb4bcd4
