apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cert-manager
  namespace: argocd

spec:

  project: default

  source:

    repoURL: https://charts.jetstack.io

    chart: cert-manager

    targetRevision: v1.18.2

    helm:
      values: |

        crds:
          enabled: true
        serviceAccount:
          create: true
          name: cert-manager
          annotations:
            iam.gke.io/gcp-service-account: cert-manager@worlddatetime-prod.iam.gserviceaccount.com
            
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

    syncOptions:
    - CreateNamespace=true