apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps-prod
  namespace: argocd

spec:
  description: Applications

  sourceRepos:
    - '*'

  destinations:
    - namespace: '*'
      server: '*'

  clusterResourceWhitelist:
    - group: '*'
      kind: '*'