apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: external-dns
  namespace: argocd

spec:

  source:

    helm:
      values: |

        provider: google

        policy: sync

        txtOwnerId: stage-cluster

        serviceAccount:
          create: true
          name: external-dns

          annotations:
            iam.gke.io/gcp-service-account: |
              externaldns@worlddatetime-stage.iam.gserviceaccount.com

        sources:
          - gateway-httproute
          - gateway-grpcroute
          - gateway-tlsroute
          - gateway-tcproute
          - gateway-udproute

        domainFilters:
          - challan.pro

  destination:
    server: https://kubernetes.default.svc
    namespace: external-dns
