apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: observability-stage
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 75.15.1

    helm:
      values: |

        grafana:

          adminPassword: admin123

          grafana.ini:

            server:
              root_url: "%(protocol)s://%(domain)s/grafana/"
              serve_from_sub_path: true

        prometheus:

          prometheusSpec:
            retention: 15d

            externalUrl: /prometheus

        alertmanager:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true