apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
  - cert-manager.yaml
  - gateways.yaml

nameSuffix: -stage

patches:
  - path: envoy-gateway-patch.yaml
    target: 
      kind: Application
      name: envoy-gateway
  - path: external-dns-patch.yaml
    target: 
      kind: Application
      name: external-dns
