apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: observability-stage
  namespace: argocd

spec:

  project: default

  source:
    repoURL: https://github.com/sverma/platform-infra.git
    targetRevision: main
    path: gitops/platform/base/observability

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
