apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherserver
spec:
  template:
    spec:
      containers:
        - name: weatherserver

          resources:
            requests:
              cpu: 200m
              memory: 256Mi

            limits:
              cpu: 1000m
              memory: 512Mi
