apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: worlddatetime-stage
  namespace: argocd

spec:
  project: apps

  source:
    repoURL: https://github.com/sverma/platform-infra.git
    targetRevision: main
    path: apps/worlddatetime/overlays/stage

  destination:
    server: https://kubernetes.default.svc
    namespace: worlddatetime

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true